# Generated by Django 4.2.11 on 2026-01-29 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("topics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("sentiment", "情感告警"),
                            ("volume", "数量告警"),
                            ("influence", "影响力告警"),
                            ("negative_ratio", "负面率告警"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="规则类型",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("greater_than", "大于"),
                            ("less_than", "小于"),
                            ("equals", "等于"),
                            ("not_equals", "不等于"),
                            ("between", "区间"),
                        ],
                        max_length=20,
                        verbose_name="条件",
                    ),
                ),
                ("threshold_value", models.FloatField(verbose_name="阈值")),
                (
                    "threshold_value_max",
                    models.FloatField(
                        blank=True,
                        help_text="区间告警时使用",
                        null=True,
                        verbose_name="最大阈值",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("critical", "紧急"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="是否启用"
                    ),
                ),
                (
                    "notify_websocket",
                    models.BooleanField(default=True, verbose_name="WebSocket通知"),
                ),
                (
                    "notify_email",
                    models.BooleanField(default=False, verbose_name="邮件通知"),
                ),
                (
                    "notify_sms",
                    models.BooleanField(default=False, verbose_name="短信通知"),
                ),
                (
                    "cooldown_minutes",
                    models.IntegerField(
                        default=30,
                        help_text="同一规则触发间隔",
                        verbose_name="冷却时间(分钟)",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "last_triggered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后触发时间"
                    ),
                ),
                (
                    "notify_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="alert_rules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="通知用户",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="topics.topic",
                        verbose_name="话题",
                    ),
                ),
            ],
            options={
                "verbose_name": "预警规则",
                "verbose_name_plural": "预警规则",
                "db_table": "alerts_alert_rule",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_value", models.FloatField(verbose_name="当前值")),
                ("threshold_value", models.FloatField(verbose_name="阈值")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("acknowledged", "已确认"),
                            ("resolved", "已解决"),
                            ("ignored", "已忽略"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("message", models.TextField(verbose_name="预警消息")),
                (
                    "details",
                    models.JSONField(blank=True, null=True, verbose_name="详细信息"),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="确认时间"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解决时间"
                    ),
                ),
                (
                    "resolution_note",
                    models.TextField(blank=True, verbose_name="处理说明"),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="触发时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="确认人",
                    ),
                ),
                (
                    "alert_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="alerts.alertrule",
                        verbose_name="预警规则",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="解决人",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_records",
                        to="topics.topic",
                        verbose_name="话题",
                    ),
                ),
            ],
            options={
                "verbose_name": "预警记录",
                "verbose_name_plural": "预警记录",
                "db_table": "alerts_alert_record",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertNotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("websocket", "WebSocket"),
                            ("email", "邮件"),
                            ("sms", "短信"),
                        ],
                        max_length=20,
                        verbose_name="通知类型",
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        help_text="用户ID、邮箱或手机号",
                        max_length=200,
                        verbose_name="接收者",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待发送"),
                            ("sent", "已发送"),
                            ("failed", "发送失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发送时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "alert_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_logs",
                        to="alerts.alertrecord",
                        verbose_name="预警记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "预警通知日志",
                "verbose_name_plural": "预警通知日志",
                "db_table": "alerts_notification_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["topic", "enabled"], name="alerts_aler_topic_i_7849be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["rule_type", "enabled"], name="alerts_aler_rule_ty_24db7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["priority", "enabled"], name="alerts_aler_priorit_fc95f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertrecord",
            index=models.Index(
                fields=["topic", "-triggered_at"], name="alerts_aler_topic_i_a84c03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertrecord",
            index=models.Index(
                fields=["status", "-triggered_at"], name="alerts_aler_status_7f016e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertrecord",
            index=models.Index(
                fields=["alert_rule", "-triggered_at"],
                name="alerts_aler_alert_r_577bd1_idx",
            ),
        ),
    ]
