# Generated by Django 4.2.11 on 2026-01-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        db_index=True,
                        help_text="设备唯一标识符",
                        max_length=50,
                        unique=True,
                        verbose_name="设备ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="设备名称")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="安装位置"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, verbose_name="描述"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "在线"),
                            ("offline", "离线"),
                            ("error", "故障"),
                            ("maintenance", "维护中"),
                        ],
                        default="offline",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "firmware_version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="固件版本"
                    ),
                ),
                (
                    "battery_level",
                    models.IntegerField(
                        blank=True,
                        help_text="百分比 0-100",
                        null=True,
                        verbose_name="电池电量",
                    ),
                ),
                (
                    "last_heartbeat",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后心跳时间"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "设备",
                "verbose_name_plural": "设备",
                "db_table": "devices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SensorType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="传感器名称")),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="传感器代码",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="如: °C, %, μg/m³", max_length=10, verbose_name="单位"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("environment", "环境监测"),
                            ("air_quality", "空气质量"),
                            ("other", "其他"),
                        ],
                        default="environment",
                        max_length=20,
                        verbose_name="分类",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="描述"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="前端使用的图标名称",
                        max_length=50,
                        verbose_name="图标",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#409EFF",
                        help_text="图表显示颜色",
                        max_length=20,
                        verbose_name="颜色",
                    ),
                ),
                (
                    "min_value",
                    models.FloatField(
                        blank=True,
                        help_text="正常范围最小值",
                        null=True,
                        verbose_name="最小值",
                    ),
                ),
                (
                    "max_value",
                    models.FloatField(
                        blank=True,
                        help_text="正常范围最大值",
                        null=True,
                        verbose_name="最大值",
                    ),
                ),
                (
                    "precision",
                    models.IntegerField(
                        default=1,
                        help_text="数据显示保留的小数位数",
                        verbose_name="小数位数",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "传感器类型",
                "verbose_name_plural": "传感器类型",
                "db_table": "sensor_types",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="DeviceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("status", "状态变更"),
                            ("control", "控制操作"),
                            ("error", "错误日志"),
                            ("info", "信息日志"),
                        ],
                        max_length=20,
                        verbose_name="日志类型",
                    ),
                ),
                ("message", models.TextField(verbose_name="日志消息")),
                (
                    "data",
                    models.JSONField(blank=True, null=True, verbose_name="附加数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="devices.device",
                        verbose_name="设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "设备日志",
                "verbose_name_plural": "设备日志",
                "db_table": "device_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
