# Generated by Django 4.2.11 on 2026-01-20 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="所有者",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="sensor_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="devices",
                to="devices.sensortype",
                verbose_name="支持的传感器",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["status"], name="devices_status_9f14cf_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["owner"], name="devices_owner_i_508ed1_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["-last_heartbeat"], name="devices_last_he_eecc16_idx"
            ),
        ),
    ]
