# Generated by Django 4.2.11 on 2026-01-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlarmNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("websocket", "WebSocket"),
                            ("email", "邮件"),
                            ("sms", "短信"),
                            ("wechat", "微信"),
                        ],
                        max_length=20,
                        verbose_name="通知类型",
                    ),
                ),
                ("recipient", models.CharField(max_length=200, verbose_name="接收人")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待发送"),
                            ("sent", "已发送"),
                            ("failed", "发送失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="发送时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "告警通知",
                "verbose_name_plural": "告警通知",
                "db_table": "alarm_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlarmRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_value", models.FloatField(verbose_name="当前值")),
                ("threshold_value", models.FloatField(verbose_name="阈值")),
                ("unit", models.CharField(max_length=10, verbose_name="单位")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("acknowledged", "已确认"),
                            ("resolved", "已解决"),
                            ("false_positive", "误报"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("critical", "严重"),
                        ],
                        max_length=20,
                        verbose_name="优先级",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="告警消息")),
                (
                    "triggered_at",
                    models.DateTimeField(db_index=True, verbose_name="触发时间"),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="确认时间"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解决时间"
                    ),
                ),
                (
                    "resolution_note",
                    models.TextField(blank=True, verbose_name="解决说明"),
                ),
                (
                    "notification_sent",
                    models.BooleanField(default=False, verbose_name="是否已发送通知"),
                ),
                (
                    "extra_data",
                    models.JSONField(blank=True, null=True, verbose_name="额外数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "告警记录",
                "verbose_name_plural": "告警记录",
                "db_table": "alarm_records",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="AlarmRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="规则名称")),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, verbose_name="描述"),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("threshold", "阈值告警"),
                            ("rate", "变化率告警"),
                            ("offline", "离线告警"),
                        ],
                        default="threshold",
                        max_length=20,
                        verbose_name="规则类型",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("greater_than", "大于"),
                            ("less_than", "小于"),
                            ("equal", "等于"),
                            ("not_equal", "不等于"),
                            ("between", "区间内"),
                            ("outside", "区间外"),
                        ],
                        max_length=20,
                        verbose_name="条件",
                    ),
                ),
                (
                    "threshold_min",
                    models.FloatField(blank=True, null=True, verbose_name="最小阈值"),
                ),
                (
                    "threshold_max",
                    models.FloatField(blank=True, null=True, verbose_name="最大阈值"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("critical", "严重"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="优先级",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "notification_enabled",
                    models.BooleanField(default=True, verbose_name="是否发送通知"),
                ),
                (
                    "delay_minutes",
                    models.IntegerField(
                        default=0,
                        help_text="持续超阈值多少分钟后触发告警",
                        verbose_name="延迟告警(分钟)",
                    ),
                ),
                (
                    "recovery_enabled",
                    models.BooleanField(default=True, verbose_name="是否告警恢复通知"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "告警规则",
                "verbose_name_plural": "告警规则",
                "db_table": "alarm_rules",
                "ordering": ["-priority", "created_at"],
            },
        ),
    ]
