# Generated by Django 4.2.11 on 2026-01-20 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        ("alarms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alarmrule",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_alarm_rules",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="alarmrule",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alarm_rules",
                to="devices.device",
                verbose_name="设备",
            ),
        ),
        migrations.AddField(
            model_name="alarmrule",
            name="sensor_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alarm_rules",
                to="devices.sensortype",
                verbose_name="传感器类型",
            ),
        ),
        migrations.AddField(
            model_name="alarmrecord",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_alarms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="确认人",
            ),
        ),
        migrations.AddField(
            model_name="alarmrecord",
            name="alarm_rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="alarms.alarmrule",
                verbose_name="告警规则",
            ),
        ),
        migrations.AddField(
            model_name="alarmrecord",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alarm_records",
                to="devices.device",
                verbose_name="设备",
            ),
        ),
        migrations.AddField(
            model_name="alarmrecord",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_alarms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="解决人",
            ),
        ),
        migrations.AddField(
            model_name="alarmrecord",
            name="sensor_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alarm_records",
                to="devices.sensortype",
                verbose_name="传感器类型",
            ),
        ),
        migrations.AddField(
            model_name="alarmnotification",
            name="alarm_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="alarms.alarmrecord",
                verbose_name="告警记录",
            ),
        ),
        migrations.AddIndex(
            model_name="alarmrecord",
            index=models.Index(
                fields=["device", "triggered_at"], name="alarm_recor_device__c66bf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alarmrecord",
            index=models.Index(fields=["status"], name="alarm_recor_status_ce9789_idx"),
        ),
        migrations.AddIndex(
            model_name="alarmrecord",
            index=models.Index(
                fields=["priority"], name="alarm_recor_priorit_9012d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alarmrecord",
            index=models.Index(
                fields=["-triggered_at"], name="alarm_recor_trigger_f39f77_idx"
            ),
        ),
    ]
