# Generated by Django 4.2.11 on 2026-01-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorDataSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary_type",
                    models.CharField(
                        choices=[
                            ("hour", "小时"),
                            ("day", "天"),
                            ("week", "周"),
                            ("month", "月"),
                        ],
                        max_length=10,
                        verbose_name="汇总类型",
                    ),
                ),
                (
                    "time_start",
                    models.DateTimeField(db_index=True, verbose_name="汇总起始时间"),
                ),
                ("time_end", models.DateTimeField(verbose_name="汇总结束时间")),
                ("avg_value", models.FloatField(verbose_name="平均值")),
                ("min_value", models.FloatField(verbose_name="最小值")),
                ("max_value", models.FloatField(verbose_name="最大值")),
                ("count", models.IntegerField(verbose_name="数据点数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_summaries",
                        to="devices.device",
                        verbose_name="设备",
                    ),
                ),
                (
                    "sensor_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_summaries",
                        to="devices.sensortype",
                        verbose_name="传感器类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "传感器数据汇总",
                "verbose_name_plural": "传感器数据汇总",
                "db_table": "sensor_data_summary",
                "ordering": ["-time_start"],
                "indexes": [
                    models.Index(
                        fields=["device", "sensor_type", "time_start"],
                        name="sensor_data_device__f0c07b_idx",
                    ),
                    models.Index(
                        fields=["time_start"], name="sensor_data_time_st_a27b94_idx"
                    ),
                ],
                "unique_together": {
                    ("device", "sensor_type", "summary_type", "time_start")
                },
            },
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField(verbose_name="数值")),
                ("unit", models.CharField(max_length=10, verbose_name="单位")),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, verbose_name="时间戳"),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("good", "良好"),
                            ("uncertain", "不确定"),
                            ("bad", "差"),
                        ],
                        default="good",
                        max_length=20,
                        verbose_name="数据质量",
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        help_text="存储额外的传感器信息",
                        null=True,
                        verbose_name="额外数据",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="接收时间"),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_data",
                        to="devices.device",
                        verbose_name="设备",
                    ),
                ),
                (
                    "sensor_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="data_records",
                        to="devices.sensortype",
                        verbose_name="传感器类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "传感器数据",
                "verbose_name_plural": "传感器数据",
                "db_table": "sensor_data",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="sensor_data_device__b1be03_idx",
                    ),
                    models.Index(
                        fields=["sensor_type", "timestamp"],
                        name="sensor_data_sensor__260b6f_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="sensor_data_timesta_ac587d_idx"
                    ),
                ],
            },
        ),
    ]
