# Generated by Django 4.2.11 on 2026-01-29 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("topics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InfluenceRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "每日"),
                            ("weekly", "每周"),
                            ("monthly", "每月"),
                        ],
                        max_length=20,
                        verbose_name="统计周期",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="日期")),
                ("top_posts", models.JSONField(default=list, verbose_name="热门帖子")),
                (
                    "top_authors",
                    models.JSONField(default=list, verbose_name="热门作者"),
                ),
                (
                    "top_keywords",
                    models.JSONField(default=list, verbose_name="热门关键词"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="influence_rankings",
                        to="topics.topic",
                        verbose_name="话题",
                    ),
                ),
            ],
            options={
                "verbose_name": "影响力排行",
                "verbose_name_plural": "影响力排行",
                "db_table": "analysis_influence_ranking",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("sentiment", "情感分析"),
                            ("keyword", "关键词提取"),
                            ("trend", "趋势分析"),
                            ("influence", "影响力分析"),
                            ("custom", "自定义分析"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="分析类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(blank=True, null=True, verbose_name="分析参数"),
                ),
                (
                    "result",
                    models.JSONField(blank=True, null=True, verbose_name="分析结果"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(blank=True, null=True, verbose_name="耗时(秒)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analysis_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_logs",
                        to="topics.topic",
                        verbose_name="话题",
                    ),
                ),
            ],
            options={
                "verbose_name": "分析日志",
                "verbose_name_plural": "分析日志",
                "db_table": "analysis_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SentimentSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot_time",
                    models.DateTimeField(db_index=True, verbose_name="快照时间"),
                ),
                (
                    "positive_count",
                    models.IntegerField(default=0, verbose_name="正面数"),
                ),
                (
                    "neutral_count",
                    models.IntegerField(default=0, verbose_name="中性数"),
                ),
                (
                    "negative_count",
                    models.IntegerField(default=0, verbose_name="负面数"),
                ),
                ("total_count", models.IntegerField(default=0, verbose_name="总数")),
                (
                    "avg_sentiment_score",
                    models.FloatField(default=0, verbose_name="平均情感分"),
                ),
                (
                    "avg_influence_score",
                    models.FloatField(default=0, verbose_name="平均影响力"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiment_snapshots",
                        to="topics.topic",
                        verbose_name="话题",
                    ),
                ),
            ],
            options={
                "verbose_name": "情感快照",
                "verbose_name_plural": "情感快照",
                "db_table": "analysis_sentiment_snapshot",
                "ordering": ["-snapshot_time"],
                "indexes": [
                    models.Index(
                        fields=["topic", "-snapshot_time"],
                        name="analysis_se_topic_i_a07c12_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="KeywordTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="关键词"
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="日期")),
                ("count", models.IntegerField(default=0, verbose_name="出现次数")),
                (
                    "sentiment_score",
                    models.FloatField(default=0, verbose_name="情感分数"),
                ),
                (
                    "platforms",
                    models.JSONField(blank=True, null=True, verbose_name="平台分布"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyword_trends",
                        to="topics.topic",
                        verbose_name="话题",
                    ),
                ),
            ],
            options={
                "verbose_name": "关键词趋势",
                "verbose_name_plural": "关键词趋势",
                "db_table": "analysis_keyword_trend",
                "ordering": ["-date", "-count"],
                "indexes": [
                    models.Index(
                        fields=["topic", "-date"], name="analysis_ke_topic_i_51f5c0_idx"
                    ),
                    models.Index(
                        fields=["keyword", "-date"],
                        name="analysis_ke_keyword_9b64e3_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="keywordtrend",
            constraint=models.UniqueConstraint(
                fields=("topic", "keyword", "date"), name="unique_keyword_date"
            ),
        ),
        migrations.AddIndex(
            model_name="influenceranking",
            index=models.Index(
                fields=["topic", "period", "-date"],
                name="analysis_in_topic_i_3c8998_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="influenceranking",
            constraint=models.UniqueConstraint(
                fields=("topic", "period", "date"), name="unique_ranking_period"
            ),
        ),
        migrations.AddIndex(
            model_name="analysislog",
            index=models.Index(
                fields=["topic", "-created_at"], name="analysis_lo_topic_i_bf1f39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analysislog",
            index=models.Index(
                fields=["analysis_type", "-created_at"],
                name="analysis_lo_analysi_336f15_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analysislog",
            index=models.Index(
                fields=["status", "-created_at"], name="analysis_lo_status_99eb7d_idx"
            ),
        ),
    ]
