# Generated by Django 4.2.11 on 2026-01-31 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0001_initial"),
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="检测时间"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("volume_spike", "数量突发"),
                            ("sentiment_shift", "情感突变"),
                            ("hotness_surge", "热度激增"),
                            ("combined", "综合异常"),
                        ],
                        max_length=50,
                        verbose_name="事件类型",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("level1", "Level 1 - 紧急"),
                            ("level2", "Level 2 - 重要"),
                            ("level3", "Level 3 - 一般"),
                        ],
                        default="level3",
                        max_length=50,
                        verbose_name="严重程度",
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        default=dict,
                        help_text="存储检测到异常的各项指标",
                        verbose_name="异常指标",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "活跃"),
                            ("resolved", "已解决"),
                            ("false_positive", "误报"),
                        ],
                        default="active",
                        max_length=50,
                        verbose_name="状态",
                    ),
                ),
                (
                    "alert_triggered",
                    models.BooleanField(default=False, verbose_name="是否触发预警"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="解决时间"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="处理备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_emergencies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理人",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_events",
                        to="topics.topic",
                        verbose_name="话题",
                    ),
                ),
            ],
            options={
                "verbose_name": "突发事件",
                "verbose_name_plural": "突发事件",
                "db_table": "analysis_emergency_event",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="PropagationPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path_data",
                    models.JSONField(
                        default=dict,
                        help_text="存储传播图的结构，包含节点和边",
                        verbose_name="传播路径数据",
                    ),
                ),
                (
                    "depth",
                    models.IntegerField(
                        default=0, help_text="传播层级数", verbose_name="传播深度"
                    ),
                ),
                (
                    "breadth",
                    models.IntegerField(
                        default=0, help_text="覆盖节点数", verbose_name="传播广度"
                    ),
                ),
                (
                    "speed",
                    models.FloatField(
                        default=0, help_text="每小时新增节点数", verbose_name="传播速度"
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        choices=[
                            ("star", "星型传播"),
                            ("chain", "链式传播"),
                            ("viral", "病毒式传播"),
                            ("community", "社区传播"),
                            ("unknown", "未知"),
                        ],
                        default="unknown",
                        max_length=50,
                        verbose_name="传播模式",
                    ),
                ),
                (
                    "key_nodes",
                    models.JSONField(
                        default=list,
                        help_text="传播中关键的节点列表",
                        verbose_name="关键节点",
                    ),
                ),
                (
                    "total_nodes",
                    models.IntegerField(default=0, verbose_name="总节点数"),
                ),
                ("total_edges", models.IntegerField(default=0, verbose_name="总边数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分析时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propagation_paths",
                        to="posts.socialpost",
                        verbose_name="原始帖子",
                    ),
                ),
            ],
            options={
                "verbose_name": "传播路径",
                "verbose_name_plural": "传播路径",
                "db_table": "analysis_propagation_path",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["post", "-created_at"],
                        name="analysis_pr_post_id_9b0cf9_idx",
                    ),
                    models.Index(
                        fields=["pattern", "-created_at"],
                        name="analysis_pr_pattern_516f9a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OpinionEvolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("latent", "潜伏期"),
                            ("germination", "萌发期"),
                            ("explosion", "爆发期"),
                            ("diffusion", "扩散期"),
                            ("decline", "衰退期"),
                            ("death", "消亡期"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="演化阶段",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="阶段开始时间"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="阶段结束时间"
                    ),
                ),
                (
                    "duration_hours",
                    models.FloatField(
                        blank=True, null=True, verbose_name="持续时长(小时)"
                    ),
                ),
                ("peak_hotness", models.FloatField(default=0, verbose_name="峰值热度")),
                ("post_count", models.IntegerField(default=0, verbose_name="帖子数")),
                (
                    "avg_sentiment",
                    models.FloatField(default=0, verbose_name="平均情感"),
                ),
                (
                    "transition_metrics",
                    models.JSONField(
                        default=dict,
                        help_text="阶段转换时的关键指标变化",
                        verbose_name="转换指标",
                    ),
                ),
                (
                    "predicted_next_stage",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="预测下一阶段"
                    ),
                ),
                (
                    "predicted_duration",
                    models.FloatField(
                        blank=True, null=True, verbose_name="预测持续时长(小时)"
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0, help_text="0-1之间", verbose_name="预测置信度"
                    ),
                ),
                (
                    "baseline_metrics",
                    models.JSONField(
                        default=dict,
                        help_text="该阶段的历史基线数据",
                        verbose_name="基线指标",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evolution_stages",
                        to="topics.topic",
                        verbose_name="话题",
                    ),
                ),
            ],
            options={
                "verbose_name": "舆情演化",
                "verbose_name_plural": "舆情演化",
                "db_table": "analysis_opinion_evolution",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["topic", "-started_at"],
                        name="analysis_op_topic_i_b360ba_idx",
                    ),
                    models.Index(
                        fields=["stage", "-started_at"],
                        name="analysis_op_stage_1d698c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="KOLProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="作者"
                    ),
                ),
                ("author_url", models.URLField(blank=True, verbose_name="作者链接")),
                (
                    "kol_type",
                    models.CharField(
                        choices=[
                            ("initiator", "发起者"),
                            ("spreader", "传播者"),
                            ("guide", "引导者"),
                            ("comprehensive", "综合影响力者"),
                        ],
                        default="comprehensive",
                        max_length=50,
                        verbose_name="KOL类型",
                    ),
                ),
                (
                    "kol_score",
                    models.FloatField(
                        db_index=True, default=0, verbose_name="KOL综合得分"
                    ),
                ),
                (
                    "content_influence",
                    models.FloatField(
                        default=0, help_text="权重40%", verbose_name="内容影响力"
                    ),
                ),
                (
                    "network_influence",
                    models.FloatField(
                        default=0, help_text="权重30%", verbose_name="网络影响力"
                    ),
                ),
                (
                    "topic_leadership",
                    models.FloatField(
                        default=0, help_text="权重20%", verbose_name="话题引领力"
                    ),
                ),
                (
                    "sentiment_influence",
                    models.FloatField(
                        default=0, help_text="权重10%", verbose_name="情感影响力"
                    ),
                ),
                ("post_count", models.IntegerField(default=0, verbose_name="帖子数")),
                (
                    "total_likes",
                    models.IntegerField(default=0, verbose_name="总点赞数"),
                ),
                (
                    "total_comments",
                    models.IntegerField(default=0, verbose_name="总评论数"),
                ),
                (
                    "total_shares",
                    models.IntegerField(default=0, verbose_name="总转发数"),
                ),
                (
                    "avg_sentiment_score",
                    models.FloatField(default=0, verbose_name="平均情感分"),
                ),
                (
                    "pagerank_score",
                    models.FloatField(default=0, verbose_name="PageRank得分"),
                ),
                (
                    "betweenness_centrality",
                    models.FloatField(default=0, verbose_name="介数中心性"),
                ),
                (
                    "closeness_centrality",
                    models.FloatField(default=0, verbose_name="接近中心性"),
                ),
                (
                    "followers_count",
                    models.IntegerField(default=0, null=True, verbose_name="粉丝数"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="是否认证"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kol_profiles",
                        to="topics.topic",
                        verbose_name="话题",
                    ),
                ),
            ],
            options={
                "verbose_name": "KOL画像",
                "verbose_name_plural": "KOL画像",
                "db_table": "analysis_kol_profile",
                "ordering": ["-kol_score"],
                "indexes": [
                    models.Index(
                        fields=["topic", "-kol_score"],
                        name="analysis_ko_topic_i_1ab39c_idx",
                    ),
                    models.Index(
                        fields=["author", "topic"], name="analysis_ko_author_a747d0_idx"
                    ),
                    models.Index(
                        fields=["kol_type", "-kol_score"],
                        name="analysis_ko_kol_typ_29666e_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="kolprofile",
            constraint=models.UniqueConstraint(
                fields=("author", "topic"), name="unique_author_topic_kol"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyevent",
            index=models.Index(
                fields=["topic", "-detected_at"], name="analysis_em_topic_i_cb749e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyevent",
            index=models.Index(
                fields=["status", "-detected_at"], name="analysis_em_status_4689ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyevent",
            index=models.Index(
                fields=["severity", "-detected_at"],
                name="analysis_em_severit_3ae2ea_idx",
            ),
        ),
    ]
