# Generated by Django 4.2.11 on 2026-01-29 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("hourly", "每小时"),
                            ("daily", "每日"),
                            ("weekly", "每周"),
                            ("monthly", "每月"),
                        ],
                        max_length=20,
                        verbose_name="统计周期",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="日期")),
                (
                    "hour",
                    models.IntegerField(blank=True, null=True, verbose_name="小时"),
                ),
                ("post_count", models.IntegerField(default=0, verbose_name="帖子数")),
                (
                    "total_likes",
                    models.IntegerField(default=0, verbose_name="总点赞数"),
                ),
                (
                    "total_comments",
                    models.IntegerField(default=0, verbose_name="总评论数"),
                ),
                (
                    "total_shares",
                    models.IntegerField(default=0, verbose_name="总转发数"),
                ),
                (
                    "total_views",
                    models.IntegerField(default=0, verbose_name="总阅读数"),
                ),
                (
                    "positive_count",
                    models.IntegerField(default=0, verbose_name="正面数"),
                ),
                (
                    "neutral_count",
                    models.IntegerField(default=0, verbose_name="中性数"),
                ),
                (
                    "negative_count",
                    models.IntegerField(default=0, verbose_name="负面数"),
                ),
                (
                    "avg_sentiment_score",
                    models.FloatField(default=0, verbose_name="平均情感分"),
                ),
                (
                    "avg_influence_score",
                    models.FloatField(default=0, verbose_name="平均影响力"),
                ),
                (
                    "max_influence_score",
                    models.FloatField(default=0, verbose_name="最高影响力"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="summaries",
                        to="topics.platform",
                        verbose_name="平台",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="topics.topic",
                        verbose_name="话题",
                    ),
                ),
            ],
            options={
                "verbose_name": "帖子汇总",
                "verbose_name_plural": "帖子汇总",
                "db_table": "posts_summary",
                "ordering": ["-date", "-hour"],
            },
        ),
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_id",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="帖子ID"
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                ("author", models.CharField(max_length=100, verbose_name="作者")),
                ("author_url", models.URLField(blank=True, verbose_name="作者链接")),
                ("post_url", models.URLField(blank=True, verbose_name="帖子链接")),
                (
                    "publish_time",
                    models.DateTimeField(db_index=True, verbose_name="发布时间"),
                ),
                ("likes", models.IntegerField(default=0, verbose_name="点赞数")),
                ("comments", models.IntegerField(default=0, verbose_name="评论数")),
                ("shares", models.IntegerField(default=0, verbose_name="转发数")),
                ("views", models.IntegerField(default=0, verbose_name="阅读数")),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "正面"),
                            ("neutral", "中性"),
                            ("negative", "负面"),
                        ],
                        db_index=True,
                        default="neutral",
                        max_length=20,
                        verbose_name="情感倾向",
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        help_text="-1到1之间，负数为负面，正数为正面",
                        null=True,
                        verbose_name="情感分数",
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        blank=True,
                        help_text="提取的关键词列表",
                        null=True,
                        verbose_name="关键词",
                    ),
                ),
                (
                    "influence_score",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        help_text="综合影响力评分",
                        verbose_name="影响力分数",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="采集时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to="topics.platform",
                        verbose_name="平台",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="topics.topic",
                        verbose_name="话题",
                    ),
                ),
            ],
            options={
                "verbose_name": "社交媒体帖子",
                "verbose_name_plural": "社交媒体帖子",
                "db_table": "posts_social_post",
                "ordering": ["-publish_time"],
                "indexes": [
                    models.Index(
                        fields=["topic", "-publish_time"],
                        name="posts_socia_topic_i_6654f7_idx",
                    ),
                    models.Index(
                        fields=["sentiment", "-publish_time"],
                        name="posts_socia_sentime_822ebe_idx",
                    ),
                    models.Index(
                        fields=["-influence_score"],
                        name="posts_socia_influen_833729_idx",
                    ),
                    models.Index(
                        fields=["platform", "-publish_time"],
                        name="posts_socia_platfor_0e25b7_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="socialpost",
            constraint=models.UniqueConstraint(
                fields=("platform", "post_id"), name="unique_platform_post"
            ),
        ),
        migrations.AddIndex(
            model_name="postsummary",
            index=models.Index(
                fields=["topic", "-date"], name="posts_summa_topic_i_480202_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postsummary",
            index=models.Index(
                fields=["topic", "period", "-date"],
                name="posts_summa_topic_i_c3a39a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postsummary",
            index=models.Index(
                fields=["platform", "-date"], name="posts_summa_platfor_c7b834_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="postsummary",
            constraint=models.UniqueConstraint(
                condition=models.Q(("platform__isnull", False)),
                fields=("topic", "platform", "period", "date", "hour"),
                name="unique_summary_period",
            ),
        ),
    ]
