# Generated by Django 4.2.11 on 2026-01-29 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="平台名称")),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("weibo", "微博"),
                            ("wechat", "微信"),
                            ("douyin", "抖音"),
                            ("zhihu", "知乎"),
                            ("bilibili", "B站"),
                            ("xiaohongshu", "小红书"),
                            ("toutiao", "今日头条"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="平台代码",
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="图标"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#409EFF", max_length=20, verbose_name="主题色"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "社交媒体平台",
                "verbose_name_plural": "社交媒体平台",
                "db_table": "topics_platform",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="话题名称"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "keywords",
                    models.JSONField(
                        default=list,
                        help_text="监控关键词列表",
                        verbose_name="关键词列表",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "监控中"),
                            ("paused", "已暂停"),
                            ("archived", "已归档"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                        default="medium",
                        max_length=20,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="topics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="负责人",
                    ),
                ),
                (
                    "platforms",
                    models.ManyToManyField(
                        blank=True,
                        related_name="topics",
                        to="topics.platform",
                        verbose_name="监控平台",
                    ),
                ),
            ],
            options={
                "verbose_name": "监控话题",
                "verbose_name_plural": "监控话题",
                "db_table": "topics_topic",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="topics_topi_status_f4882b_idx",
                    ),
                    models.Index(
                        fields=["priority", "status"],
                        name="topics_topi_priorit_4a1418_idx",
                    ),
                ],
            },
        ),
    ]
